[package]
name = "tracem"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.69.4"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
libc = "0.2.153"
log = "0.4.21"
mio = { version = "0.8.11", features = ["os-ext", "os-poll"] }
